# Generated by Django 3.0.3 on 2020-03-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20200312_1504'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
