# Generated by Django 3.0.3 on 2020-03-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctordetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slots', models.TimeField()),
                ('is_booked', models.CharField(default='N', max_length=1)),
            ],
        ),
    ]
