# Generated by Django 3.0.3 on 2020-03-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorslots',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
