# Generated by Django 3.0.3 on 2020-03-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorslots',
            name='is_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Appointments',
        ),
    ]
