# Generated by Django 3.0.3 on 2020-03-13 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_auto_20200314_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='slot_id',
            new_name='slot',
        ),
    ]
