# Generated by Django 3.0.3 on 2020-03-14 16:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_auto_20200314_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorslots',
            name='slot_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 14, 16, 38, 20, 956144, tzinfo=utc)),
        ),
    ]
